FROM pantsel/konga:next

MAINTAINER linjiancheng (sys.linjc@gmail.com)

# KONG_DATABASE: mongo,mysql,postgres
ENV DB_ADAPTER='postgres' \
DB_HOST='127.0.0.1' \
DB_PORT='1921' \
DB_USER='postgres' \
DB_PASSWORD='postgres' \
TOKEN_SECRET='km1GUr4RkcQD8DewhJPNXrCuZwcKmqjb' \
DB_DATABASE='postgres' \
NODE_ENV='production'

